# Generated by Django 3.1.6 on 2021-03-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210226_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='intro',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
