# Generated by Django 3.1.6 on 2021-03-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210304_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
