# Generated by Django 3.1.6 on 2021-03-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_userinfo_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='type',
        ),
        migrations.AddField(
            model_name='social',
            name='stype',
            field=models.CharField(default='Social Media', max_length=20),
        ),
    ]
