# Generated by Django 3.1.6 on 2021-03-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_social_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='link',
        ),
    ]
