# Generated by Django 3.1.6 on 2021-03-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_social_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profession',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
