# Generated by Django 3.1.6 on 2021-03-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_social_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.userinfo'),
        ),
    ]
