# Generated by Django 3.1.6 on 2021-03-11 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210311_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dob',
            field=models.DateField(default=datetime.date(2021, 3, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profession',
            field=models.CharField(default='Engineer', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
