# Generated by Django 3.1.6 on 2021-03-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20210314_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
    ]
